# cfg-exporter 配置模板

# 配置文件路径
source = "./samples/configs"
# 字段描述行号
field_comment_row = 1
# 字段类型行号
field_type_row = 2
# 字段装饰器行号
field_decorator_row = 3
# 主体数据起始行号
body_start_row = 6
# 是否检验生成后的配置
verify = false

# 内部sqlite数据库目录
sqlite_directory = "./samples/sqlite"

# Erlang导出配置
[schema.erlang]
# 文件前缀
file_prefix = "cfg_"
# 表名前缀
table_name_prefix = "cfg_"
# 字段名行号
field_name_row = 5
# hrl导出目录
hrl_directory = "./samples/erlang/hrl"
# erl导出目录
erl_directory = "./samples/erlang/erl"
# 模板目录
erl_template_directory = "./templates/erlang"

# typescript导出配置
[schema.typescript]
# 文件前缀
file_prefix = ""
# 表名前缀
table_name_prefix = ""
# 字段名行号
field_name_row = 4
# 导出目标路径
ts_directory = "./samples/typescript"
# 方法名以驼峰命名 默认：不做转换
ts_method_in_camel_case = false

# json导出配置
[schema.json]
# 文件前缀
file_prefix = ""
# 表名前缀
table_name_prefix = ""
# 字段名行号
field_name_row = 4
# 导出目标路径
json_directory = "./samples/json"

# flatbuffers导出配置
[schema.flatbuffers]
# 文件前缀
file_prefix = ""
# 表名前缀
table_name_prefix = "fbs_"
# 字段名行号
field_name_row = 4
# flatc可执行文件的位置
flatc = "./samples/flatbuffers/flatc.exe"
# fbs描述文件导出目录
fbs_directory = "./samples/flatbuffers/fbs"
# 序列化文件导出目录
bin_directory = "./samples/flatbuffers/bin"
# 命名空间
namespace = "xcel_flow"